### ISSUE TITLE
showFileSelection() to only allow specific file extension

### ISSUE THREAD

**Issue by Iqwertz** [Milchreis/uibooster-for-processing#11]
Is there an option to allow the file Selection to only allow a specific file extension? I
It would be great if this would be an optional Parameter to pass to this function

**Comment by Milchreis** [comment]
hi @Iqwertz,

thank you for your request. It's a very good idea 😊 I added a new issue in the main repo in [UiBooster](https://github.com/Milchreis/UiBooster/issues/32). Please follow this issue to be update, because I will close this one. Here in this repo I collect issues which are specific for the processing environment.

**Comment by Iqwertz** [comment]
Oh okay! Thank you
