### ISSUE TITLE
Not working with P3D mode

### ISSUE THREAD

**Issue by hiorws** [Milchreis/uibooster-for-processing#5]
As far as I understand, the library is not working with Processing's P3D mode.
I tried the examples with just changing the mode to `P3D`.

Is the P3D support in the current development plan?

By the way, I really like the simplicity of the usage.
Thanks for all.

**Comment by Milchreis** [comment]
hi @hiorws 
I tried the form and selection examples with P3D and I can't find any issues. For me on windows it works fine with P3D.

What example did you use and what kind of error did you get?

**Comment by hiorws** [comment]
Hi @Milchreis I tried most of the examples including form and selections. None of them are not working. The behavior is the same. I think it's not about the components.

Actually, it's not giving any error or warning. The sketch hangs when the `booster.showXXXX()` function called and nothing happens.

I'm using macOS Catalina 10.15.4 and Processing version is 3.5.4

Thanks for your attention.

**Comment by Milchreis** [comment]
Ok, I understand. The most dialogs of UiBooster are blocking and are stopping the main loop. It's because the the dialog expects an user input and return its value. In the most cases is fine, especially for small application. In processing it's different. There is a running draw loop and it's stopped by UiBooster and you notice the interruption. This behavious is currently normal, even in P2D.

If you want a non blocking dialog you have to use the Form with the `run` method. In the [javadoc method description](https://milchreis.github.io/uibooster-for-processing/reference/uibooster/UiBooster.html) is defined if a dialog is blocking.
